### ISSUE TITLE
Publish to krew

### ISSUE THREAD

**Issue by applejag** [jadolg/szero#97]
Would be nice to have it in krew

You can take inspiration from here: <https://github.com/applejag/kubectl-klock/blob/main/.krew.yaml>

Maybe something like this works, though I have not confirmed it:

```yaml
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jadolg/szero
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jadolg/szero/releases/download/{{ .TagName }}/szero_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./szero"
      to: "./kubectl-szero"
    - from: LICENSE
      to: "."
    bin: "kubectl-szero"

```
